from __future__ import annotations

from typing import Annotated, List, Literal, Dict, Optional, Union, Tuple

from pydantic import BaseModel, Field

from .decomposition import (
    AtomicBlock,
    Scenario,
    AtomicBlockList,
    GrammaticalBlockList,
    LocalizedScenario,
)
from langchain_core.messages import BaseMessage


class AgentState(BaseModel):
    messages: Annotated[
        List[Union[BaseMessage, Dict[str, str]]], "List of messages (Human/AI/Tool)"
    ] = Field(default_factory=list)
    iterations: Annotated[int, "The current iteration number of the agent"] = 0

    # Tool logging
    tool_calls: Annotated[
        Dict[str, Dict[str, int]],
        "Mapping: tool name -> encoded argument -> count of calls",
    ] = Field(default_factory=dict)
    curr_tool_trajectory: List[str] = Field(default_factory=list)
    tool_trajectories: List[List[str]] = Field(default_factory=list)

    # Inputs
    grammatical_blocks: Annotated[
        Optional[GrammaticalBlockList],
        "Input grammatical blocks when using grammatical mode",
    ] = None
    scenario: Annotated[
        Optional[Scenario],
        "Input Scenario when using Gherkin mode",
    ] = None

    # For test packaging
    package: Annotated[
        Optional[str], "The package selected by the agent for the test code."
    ] = None
    class_name: Annotated[
        Optional[str], "The test class name selected by the agent."
    ] = None
    method_signature: Annotated[
        Optional[str],
        "The annotation-qualified test method signature generated by the agent.",
    ] = None

    # Outputs
    atomic_blocks: Annotated[
        Optional[AtomicBlockList], "The current state of the AtomicBlocks"
    ] = None
    localized_scenario: Annotated[
        Optional[LocalizedScenario],
        "Finalized LocalizedScenario produced by localization",
    ] = None
    final_comments: Annotated[
        Optional[str], "Final comments from the agent, if any"
    ] = ""
    finalize_called: Annotated[
        bool,
        "True when the agent has successfully called the finalize tool for this run.",
    ] = False
    force_end_attempts: Annotated[
        int,
        "Number of times the agent has entered the force_end node to coerce finalization.",
    ] = 0

    def reset_message_history(self) -> None:
        """Reset tracked conversation history between agent invocations."""
        self.iterations = 0
        self.final_comments = ""
        self.finalize_called = False
        self.force_end_attempts = 0
        self.messages = (
            []
        )  # TODO: Maybe have some functionality for summarizing this instead of clearing
        self.tool_calls = {}
        self.curr_tool_trajectory.clear()
        self.tool_trajectories.clear()


class QueryMethodArgs(BaseModel):
    qualified_class_name: Annotated[
        str,
        Field(
            description="The qualified class name of the class implementing the method."
        ),
    ]
    method_signature: Annotated[
        str, Field(description="The method signature of the method to query.")
    ]


class QueryClassArgs(BaseModel):
    qualified_class_name: Annotated[
        str, Field(description="The qualified class name of the class to query.")
    ]


class QueryVectorDataArgs(BaseModel):
    query: Annotated[str, Field(description="The query string to search for.")]
    i: Annotated[int, Field(gt=0, description="1-based start rank, must be > 0.")]
    j: Annotated[
        int,
        Field(ge=1, description="1-based end rank (inclusive), must be >= i."),
    ]


class ReachableMethodsArgs(BaseModel):
    qualified_class_name: Annotated[
        str,
        Field(
            description="The fully qualified class name to list reachable methods from."
        ),
    ]
    visibility_mode: Annotated[
        Literal["public", "same_package", "same_package_or_subclass"],
        Field(description="The visibility mode of the reachable methods."),
    ]


class InstructionArgs(BaseModel):
    instructions: Annotated[
        str, Field(description="The instructions for the modification.")
    ]
    current_blocks: Annotated[
        AtomicBlockList, Field(description="The current state of the AtomicBlocks.")
    ]
    # NOTE: We don't need to pass in the atomic blocks here for modify_atomic_blocks because we're using the state.atomic_blocks


class GenerateTestCodeArgs(BaseModel):
    """Arguments for providing raw test code directly to the generate tool."""

    test_code: Annotated[str, Field(description="")]
    qualified_class_name: Annotated[
        str, Field(description="The fully qualified class name for the test class.")
    ]
    method_signature: Annotated[
        str,
        Field(
            description=(
                "The single test method signature annotated as a test within the generated code."
            )
        ),
    ]


class FinalizeCommentsArgs(BaseModel):
    """Arguments for finalizing the composition process with comments only."""

    comments: Annotated[
        str,
        Field(
            description="Comments about any problems with the procedure or concerns."
        ),
    ]


class FinalizeAtomicBlockArgs(BaseModel):
    current_blocks: Annotated[
        AtomicBlockList, Field(description="The current state of the AtomicBlocks.")
    ]
    comments: Annotated[
        str,
        Field(
            description="Comments about any problems with the procedure or concerns."
        ),
    ]
    # NOTE: We don't need to pass in the atomic blocks here because we're using the state.atomic_blocks


class ModifyAtomicBlockNotesArgs(BaseModel):
    order: Annotated[int, Field(description="The order of the atomic block to modify.")]
    new_notes: Annotated[str, Field(description="The new notes for the atomic block.")]


class FinalizeScenarioArgs(BaseModel):
    scenario: Annotated[
        LocalizedScenario,
        Field(description="The current LocalizedScenario to finalize."),
    ]
    comments: Annotated[
        str,
        Field(
            description="Comments about any problems with the procedure or concerns."
        ),
    ]


class ModifyScenarioArgs(BaseModel):
    """Arguments for modifying a localized scenario in composition tools."""

    scenario: Annotated[LocalizedScenario, Field(description="")]


class ModifyAtomicBlocksArgs(BaseModel):
    """Arguments for modifying atomic blocks in composition tools."""

    atomic_blocks: Annotated[AtomicBlockList, Field(description="")]


class ModifyScenarioCommentArgs(BaseModel):
    id: Annotated[int, Field(description="The id of the localized step to update.")]
    comment: Annotated[str, Field(description="The new comment for the step.")]


class ViewTestCodeArgs(BaseModel):
    start_line: Annotated[int, Field(ge=1, description="1-based start line to slice the returned source.")]
    end_line: Annotated[int, Field(ge=1, description="1-based end line to slice the returned source.")]


class ModifyAtomicBlockNoteArgs(BaseModel):
    order: Annotated[int, Field(description="The order of the atomic block to update.")]
    note: Annotated[str, Field(description="The new note for the atomic block.")]


class ExtractMethodCodeArgs(BaseModel):
    qualified_class_name: Annotated[
        str, Field(description="The fully qualified class name of the class containing the method.")]
    method_signature: Annotated[str, Field(description="The method signature of the method whose code to extract.")]
    start_line: Annotated[int, Field(ge=1, description="1-based start line to slice the returned source.")]
    end_line: Annotated[int, Field(ge=1, description="1-based end line to slice the returned source.")]


class NoArgs(BaseModel):
    """Empty args schema for tools that take no arguments.

    Intentionally contains no fields. Tools must not rely on defaults.
    """
    pass


class CallAgentGherkinArgs(BaseModel):
    """Arguments for delegating from Supervisor to agents in Gherkin mode."""

    blocks: Annotated[
        LocalizedScenario,
        Field(description="The current LocalizedScenario to operate on."),
    ]
    instructions: Annotated[
        str,
        Field(description="Actionable instructions for the delegated agent."),
    ]


class CallAgentGrammaticalArgs(BaseModel):
    """Arguments for delegating from Supervisor to agents in Grammatical mode."""

    blocks: Annotated[
        AtomicBlockList,
        Field(description="The current AtomicBlockList to operate on."),
    ]
    instructions: Annotated[
        str,
        Field(description="Actionable instructions for the delegated agent."),
    ]
