[project]
name = "sakura"
version = "0.0.1"
description = "ASTER-Sakura: [A]utomated Natural Language to Te[s][t] Cas[e] Generato[r]"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "beautifulsoup4>=4.12.0,<5.0.0",
    "joblib==1.4.2",
    "rich==14.0.0",
    "tqdm>=4.66.1,<5.0.0",
    "requests>=2.32.0,<3.0.0",
    "javalang==0.13.0",
    "toml>=0.10.2,<0.11.0",
    "jinja2>=3.1.2,<4.0.0",
    "openai>=1.12.0,<2.0.0",
    "python-dotenv>=1.0.1,<2.0.0",
    "cldk==1.0.6",
    "plotly>=5.22.0,<6.0.0",
    "matplotlib>=3.9.0,<4.0.0",
    "openpyxl==3.0.9",
    "replicate>=1.0.3,<2.0.0",
    "tree-sitter-java>=0.23.5,<0.24.0",
    "deepdiff>=8.0.1,<9.0.0",
    "typer>=0.15.3,<0.17.0",
    "hamster @ git+ssh://git@github.com/aster-test-generation/hamster.git@main",
    "langchain>=0.3.26,<0.4.0",
    "faiss-cpu>=1.11.0,<2.0.0",
    "langchain-community>=0.3.26,<0.4.0",
    "langgraph>=0.5.4,<0.6.0",
    "langchain-openai>=0.3.30,<0.4.0",
    "google-cloud-aiplatform>=1.74.0,<2.0.0",
    "pyright>=1.1.407,<2.0.0",
    "tenacity>=9.0.0,<10.0.0",
]

[project.scripts]
sakura = "sakura.cli:app"

[dependency-groups]
dev = [
    "black>=24.3.0,<25.0.0",
    "pytest>=8.2.0,<9.0.0",
    "pytest-cov>=4.1.0,<5.0.0",
    "pylint>=3.0.2,<4.0.0",
    "flake8>=6.1.0,<7.0.0",
    "coverage>=7.3.2,<8.0.0",
    "pyinstaller>=6.6.0,<7.0.0",
    "ollama>=0.5.1,<0.6.0",
    "pyright>=1.1.407,<2.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/sakura"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
addopts = "-vv -s --tb=long"
